name: Build and Release Wheels (CPU)

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]  # ubuntu-24.04 пока недоступен
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Clone llama-cpp-python
        run: |
          git clone --branch main https://github.com/abetlen/llama-cpp-python.git llama_src
          cd llama_src
          git submodule update --init --recursive
        shell: bash

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          python -m uv pip install -e .[all] --verbose

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_BUILD: "cp311-* cp312-*"  # Только Python 3.11 и 3.12
        with:
          package-dir: .  # Исходники уже в корне
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  release:
    name: Release
    needs: [build_wheels]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}-cpu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
