name: Build and Release Wheels (CPU)

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4  # Важно: оставляем пустой репозиторий

      - name: Clone llama-cpp-python
        run: |
          git clone --depth 1 --branch main https://github.com/abetlen/llama-cpp-python.git llama_src
          cd llama_src
          git submodule update --init --recursive
          ls -la  # Проверяем наличие pyproject.toml
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel cmake scikit-build

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_REPAIR_WHEEL_COMMAND: ""
        with:
          package-dir: llama_src  # Указываем явно путь к исходникам
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: ./wheelhouse/*.whl

  release:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*.whl
          tag_name: ${{ github.ref_name }}-cpu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
